### ISSUE TITLE
Bump to the latest dependency versions

### ISSUE THREAD

**Issue by mdv27** [adam-cowley/nest-neo4j#14]
Could you please update the dependency versions to their latest or at least make compatible with higher version?

**Comment by maximeSurmontGH** [comment]
Same request here :)

**Comment by adam-cowley** [comment]
Let me know if version 0.2.0 solves this issue for you :)

**Comment by maximeSurmontGH** [comment]
Perfect, bump to neo4j-driver 5.1.0 easily

**Comment by adam-cowley** [comment]
Annoyingly that version was released about an hour after I merged the PR
