### ISSUE TITLE
Need connectivity support for AuraDB in Neo4jConfig

### ISSUE THREAD

**Issue by Chakravarthy7102** [adam-cowley/nest-neo4j#18]
Currently the present config:Neo4jConfig for connecting to "nest-neo4j" to the db, doesn't support for AuraDB url's , as it is supporting the selfhosted connections only.

**Comment by adam-cowley** [comment]
You should be able to use `neo4j+s` as the scheme and the aura connection uri, let me double-check.  The driver needs updating to the latest version anyway.

**Comment by Chakravarthy7102** [comment]
Thanks, Yes it' s started working after changing to `neo4j+s`, but it would be nice to just only pass the connection uri directly in to the config object.

**Comment by adam-cowley** [comment]
Yeah, this is a bit of a hangover from pre-aura days when it made sense to define the scheme specifically.  The `fromEnv()` method should also be capable of reading the credentials.env file that is downloaded from the Aura console.  One day, maybe!

**Comment by Chakravarthy7102** [comment]
Ohh that would be nice, I will try to add that utility in my free time!
